external-dns:
  provider: ovh
  logLevel: debug
  env:
  - name: OVH_APPLICATION_KEY
    valueFrom:
      secretKeyRef:
        name: ovh-credentials
        key: OVH_APPLICATION_KEY
  - name: OVH_APPLICATION_SECRET
    valueFrom:
      secretKeyRef:
        name: ovh-credentials
        key: OVH_APPLICATION_SECRET
  - name: OVH_CONSUMER_KEY
    valueFrom:
      secretKeyRef:
        name: ovh-credentials
        key: OVH_CONSUMER_KEY

  domainFilters:
  - leogout.fr
  sources:
  - ingress
