global:
  # -- Default domain used by all components
  ## Used for ingresses, certificates, SSO, notifications, etc.
  domain: argocd.leogout.fr

configs:
  params:
    server.insecure: true

server:
  ingress:
    enabled: true
    ingressClassName: "nginx"
    hosts:
      - argocd.leogout.fr
