argo-cd:
  global:
    domain: argocd.leogout.fr

  configs:
    params:
      server.insecure: true

  server:
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        nginx.ingress.kubernetes.io/ssl-passthrough: "true"
      tls: true
