apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-addons
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/leogout/kube-ovh.git
        revision: HEAD
        tags:
          - pattern: 'v.*'
  template:
    metadata:
      name: '{{path.basename}}-{{tag}}'
      namespace: argocd
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      source:
        repoURL: https://github.com/leogout/kube-ovh.git
        targetRevision: '{{tag}}'
        # Le chemin vers le chart Helm est le chemin du répertoire découvert par le générateur Git
        path: 'addons/{{path.basename}}' # Cela se résoudra en "addons/cert-manager", "addons/ingress-nginx", etc.
        # Pas besoin de helm.values ici car les values sont contenues dans mes charts helm
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
