apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: random-jdr
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: random-jdr=ghcr.io/leogout/random-jdr-backend
    argocd-image-updater.argoproj.io/random-jdr.update-strategy: semver
    argocd-image-updater.argoproj.io/random-jdr.allow-tags: regexp:^v[0-9]+\.[0-9]+\.[0-9]+$
    argocd-image-updater.argoproj.io/random-jdr.helm.image-spec: github.tag
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: main
spec:
  project: default
  source:
    repoURL: https://github.com/leogout/random-dnd.git
    path: helm
    targetRevision: "v*"
    helm:
      valueFiles:
        - values.yaml
      values: |
        github:
          repository_owner: leogout
          tag: main
  destination:
    namespace: random-jdr
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true # ArgoCD will create the namespace if it doesn't exist
      - ApplyOutOfSyncOnly=true # Only apply changes to out-of-sync resources (useful for large apps)
      - Replace=true # Replace existing resources if they are immutable
